name: Build and Deploy to GCP - DEV
on:
  workflow_call:
    secrets:
      GCP_CONTAINER_REGISTRY:
        required: true
      GCP_PROJECT_ID_DEV:
        required: true
      GCP_CREDENTIALS_DEV:
        required: true
    inputs:
      service:
        type: string
        required: true
      sha:
        type: string
        required: true
env:
  SERVICE: ${{ inputs.service }}-develop
  CONTAINER_REGISTRY: ${{ secrets.GCP_CONTAINER_REGISTRY }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
  IMAGE: ${{ secrets.GCP_CONTAINER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID_DEV }}/${{ inputs.service }}-develop:${{ inputs.sha }}
  CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_DEV }}
  ENVIRONMENT: DEV
jobs:
  validate-composer:
    name: Validate / Composer
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Validating composer.json and composer-lock.json
        run: composer validate --strict
  validate-composer-cache:
    name: Validate / Composer Cache
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Validating composer cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-
  validate-install-dependencies:
    name: Validate / Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Validating dependencies
        run: composer install --prefer-dist --no-progress
  validate-phpmd:
    name: Validate / PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Executing PHPMD
        uses: GeneaLabs/action-reviewdog-phpmd@1.0.0
        with:
          github_token: ${{ github.token }}
          level: warning
          reporter: github-check
          standard: cleancode,codesize,controversial,design,naming,unusedcode
          target_directory: app
  test-unit:
    needs:
      - validate-composer
      - validate-composer-cache
      - validate-install-dependencies
      - validate-phpmd
    name: Test / Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: composer install --no-progress
      - name: Gerenate keys
        run: php artisan passport:keys --force
      - name: Run unit tests
        run: composer run test-unit
  test-feature:
    needs:
      - validate-composer
      - validate-composer-cache
      - validate-install-dependencies
      - validate-phpmd
    name: Test / Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: composer install --no-progress
      - name: Gerenate keys
        run: php artisan passport:keys --force
      - name: Run unit tests
        run: composer run test-feature
  settings:
    needs:
      - test-unit
      - test-feature
    name: Load application settings
    runs-on: ubuntu-latest
    outputs:
      port: "${{ fromJSON(steps.settings.outputs.output).settings.port }}"
      region: "${{ fromJSON(steps.settings.outputs.output).settings.region }}"
      scalling-concurrency: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.concurrency }}"
      scalling-min-instances: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.min-instances }}"
      scalling-max-instances: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.max-instances }}"
      scalling-timeout: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.timeout }}"
      scalling-memory: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.memory }}"
      scalling-cpu: "${{ fromJSON(steps.settings.outputs.output).settings.scalling.cpu }}"
      enable-ssl: "${{ fromJSON(steps.settings.outputs.output).settings.enable-ssl }}"
      ingress: "${{ fromJSON(steps.settings.outputs.output).settings.ingress }}"
      cpu-throttling: "${{ fromJSON(steps.settings.outputs.output).settings.cpu-throttling }}"
      execution-environment: "${{ fromJSON(steps.settings.outputs.output).settings.execution-environment }}"
      instances: "${{ steps.sql-instances-sockets-handler.outputs.instances }}"
      custom-command: "${{ fromJSON(steps.settings.outputs.output).settings.custom-command }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load environment application settings
        id: settings
        uses: fabasoad/data-format-converter-action@main
        with:
          input: ./infra/config/${{ env.ENVIRONMENT }}.yml
          from: yaml
          to: json
      - name: SQL instances sockets handler
        id: sql-instances-sockets-handler
        run: |
          instances=($(echo '${{ toJSON(fromJSON(steps.settings.outputs.output).settings.instances) }}' | sed -e "s/,/ /g" -e "s/[]['\"]//g"))
          echo "instances="$(IFS=,; echo "${instances[*]}") >> $GITHUB_OUTPUT
  deploy:
    needs: settings
    name: Deploy to DEV
    environment:
      name: DEV
      url: ${{ steps.output.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.CREDENTIALS }}
      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.CONTAINER_REGISTRY }} --quiet
      - name: Build
        run: docker build -t ${{ env.IMAGE }} . -f app.dockerfile --build-arg APP_ENV=${{ env.ENVIRONMENT }}
      - name: Push
        run: docker push ${{ env.IMAGE }}
      - name: Deploy
        run: gcloud run deploy ${{ env.SERVICE }} --image ${{ env.IMAGE }} --region ${{ needs.settings.outputs.region }} --memory ${{ needs.settings.outputs.scalling-memory }} --min-instances ${{ needs.settings.outputs.scalling-min-instances }} --max-instances ${{ needs.settings.outputs.scalling-max-instances }} --platform managed --port ${{ needs.settings.outputs.port }} --timeout ${{ needs.settings.outputs.scalling-timeout }} --set-env-vars "ENABLE_SSL=${{ needs.settings.outputs.enable-ssl }}" --execution-environment ${{ needs.settings.outputs.execution-environment }} --ingress ${{ needs.settings.outputs.ingress }} --cpu ${{ needs.settings.outputs.scalling-cpu }} --concurrency ${{ needs.settings.outputs.scalling-concurrency }} ${{ (needs.settings.outputs.cpu-throttling && '--cpu-throttling') || '--no-cpu-throttling' }} --service-account ${{ env.PROJECT_ID }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com --allow-unauthenticated --add-cloudsql-instances=${{ needs.settings.outputs.instances }}
      - name: Ouput
        run: echo "url="$(gcloud run services describe ${{ env.SERVICE }} --platform managed --region ${{ needs.settings.outputs.region }} --format 'value(status.url)') >> $GITHUB_OUTPUT
        id: output
  custom-command-execution:
    needs:
      - settings
      - deploy
    name: Custom command execution
    runs-on: ubuntu-latest
    if: ${{ needs.settings.outputs.custom-command != '' }}
    steps:
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.CREDENTIALS }}
      - name: Check if jobs exists
        id: status
        run: echo "status="$(gcloud beta run jobs describe ${{ env.SERVICE }} --region ${{ needs.settings.outputs.region }} --format 'value(status.conditions.status)') >> $GITHUB_OUTPUT
      - name: Create job if not exists
        if: ${{ steps.status.outputs.status != 'True' }}
        run: gcloud beta run jobs create ${{ env.SERVICE }} --image ${{ env.IMAGE }} --region ${{ needs.settings.outputs.region }}
      - name: Update job
        run: gcloud beta run jobs update ${{ env.SERVICE }} --image ${{ env.IMAGE }} --region ${{ needs.settings.outputs.region }} --args="${{ needs.settings.outputs.custom-command }}" --max-retries 0 --task-timeout 180 --add-cloudsql-instances=${{ needs.settings.outputs.instances }}
      - name: Execute job
        run: gcloud beta run jobs execute ${{ env.SERVICE }} --region ${{ needs.settings.outputs.region }} --wait
