name: Deploy maven package to GitHub Repository
on:
  workflow_call:
    inputs:
      username:
        type: string
        required: true
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Deploy
        run: mvn deploy -Drepo.username=${{ inputs.username }} -Drepo.password=${{ secrets.GITHUB_TOKEN }}
